### ISSUE TITLE
XPS to PDF conversion not working in NET6

### ISSUE THREAD

**Issue by HelmuthWcs** [HiraokaHyperTools/PDFsharp#22]
I'm running the same code for NET5 and NET6, and I have confirmed that this code is working in NET5 but not in NET6:

`using (XpsDocument xpsDoc = new XpsDocument(path, FileAccess.Write))
{
	XpsDocumentWriter xWriter = XpsDocument.CreateXpsDocumentWriter(xpsDoc);
	xWriter.Write(page);
}
PdfSharp.Xps.XpsConverter.Convert(path, fileName, 0);`

The XPS file seems fine, but the conversion results in blank space where the text should be. Images render without issue.

I am running kenjiuno.PdfSharp.Xps version 1.1.9 and kenjiuno.PdfSharp-WPF version 1.31.6034

**Comment by kenjiuno** [comment]
Thanks for reporting, I'll check this later

**Comment by kenjiuno** [comment]
Ok 1.1.10 will resolve this.
https://www.nuget.org/packages/kenjiuno.PdfSharp.Xps

**Comment by HelmuthWcs** [comment]
It works. Thanks!

**Comment by kenjiuno** [comment]
Thx for checking, now closing
