### ISSUE TITLE
App window scales down when executing XpsConverter.Convert()

### ISSUE THREAD

**Issue by hiwilfried** [HiraokaHyperTools/PDFsharp#27]
Hello!
I have a VB.net Windows Forms app (.net Framework 4.6), in which I use kenjiuno.PdfSharp.Xps (current version on NuGet is 1.1.12) to convert an Xps document to PDF. The issue is, that when the program executes
`PdfSharp.Xps.XpsConverter.Convert(pXpsFilename)`
the app window scales down on certain systems. When the Windows display scaling factor is 150%, the app window scales down to 100%. When display scaling factor is 100%, the app window scales down to somewhat 66%, so it's unusable afterwards.
On Windows 11, the error does not occur. But I can reproduce the error on Windows 10 with scaling factor 150% and on Windows Server 2019 in the remote desktop environment.
I cannot image, what the conversion has to do with app window scaling, but there must be a connection.

**Comment by kenjiuno** [comment]
Hi, I have confirmed the situation that you have described.

This DWM scaling change on application occurs when it loads WPF DLLs.

```
'WindowsFormsApp16.exe' (CLR v4.0.30319: WindowsFormsApp16.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\ReachFramework\v4.0_4.0.0.0__31bf3856ad364e35\ReachFramework.dll'. 
'WindowsFormsApp16.exe' (CLR v4.0.30319: WindowsFormsApp16.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework\v4.0_4.0.0.0__31bf3856ad364e35\PresentationFramework.dll'. 
'WindowsFormsApp16.exe' (CLR v4.0.30319: WindowsFormsApp16.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\WindowsBase\v4.0_4.0.0.0__31bf3856ad364e35\WindowsBase.dll'. 
'WindowsFormsApp16.exe' (CLR v4.0.30319: WindowsFormsApp16.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_32\PresentationCore\v4.0_4.0.0.0__31bf3856ad364e35\PresentationCore.dll'. 
'WindowsFormsApp16.exe' (CLR v4.0.30319: WindowsFormsApp16.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xaml\v4.0_4.0.0.0__b77a5c561934e089\System.Xaml.dll'. 
```

So there is no good way to avoid this by default.

It needs a workaround on your application.

Add `app.manifest`:

![2024-09-10_14h47_23](https://github.com/user-attachments/assets/432afd8d-c647-410c-894c-3f691ea826ca)

And also ensure `app.manifest` is active:

![2024-09-10_14h50_33](https://github.com/user-attachments/assets/3845e2d3-e562-4677-8fe4-ccdabfa527b7)

Set `<dpiAware />` to `false`

```xml
  <!-- Indicates that the application is DPI-aware and will not be automatically scaled by Windows at higher
       DPIs. Windows Presentation Foundation (WPF) applications are automatically DPI-aware and do not need 
       to opt in. Windows Forms applications targeting .NET Framework 4.6 that opt into this setting, should 
       also set the 'EnableWindowsFormsHighDpiAutoResizing' setting to 'true' in their app.config. 
       
       Makes the application long-path aware. See https://docs.microsoft.com/windows/win32/fileio/maximum-file-path-limitation -->
  <application xmlns="urn:schemas-microsoft-com:asm.v3">
    <windowsSettings>
      <dpiAware xmlns="http://schemas.microsoft.com/SMI/2005/WindowsSettings">false</dpiAware>
    </windowsSettings>
  </application>
```

Probably this can avoid your issue.

**Comment by hiwilfried** [comment]
It worked. Thank you very much for your help.
