### ISSUE TITLE
v1.1.13 won't stretch the image

### ISSUE THREAD

**Issue by tp1415926535** [HiraokaHyperTools/PDFsharp#29]
From the `.xps` file everything looks good, but once converted to `.pdf`, images will not stretch while use the original size. 

Tested many times and found that [kenjiuno.PdfSharp.Xps](https://www.nuget.org/packages/kenjiuno.PdfSharp.Xps) 1.1.13 causes this, once back to 1.1.12 everything is fine...

**Comment by kenjiuno** [comment]
Thanks for reporting.

I have confirmed that there are differences about xps2pdf conversion between 1.1.13 and 1.1.12 by using xps sample files available at https://github.com/HiraokaHyperTools/SampleXpsDocuments_1_0

<img width="512" alt="2024-11-02_11h44_20" src="https://github.com/user-attachments/assets/7b134314-6a62-457a-84e1-bd9c7ffec851">


I'll check this.

**Comment by kenjiuno** [comment]
The problem should be fixed, please try
https://www.nuget.org/packages/kenjiuno.PdfSharp.Xps/1.1.14

**Comment by tp1415926535** [comment]
> The problem should be fixed, please try https://www.nuget.org/packages/kenjiuno.PdfSharp.Xps/1.1.14

In my case, the v1.1.14 image looks like it scaled properly, but was cropped by its original size.
![image](https://github.com/user-attachments/assets/c612b253-2641-42f3-8ee2-0ec544fa13bf)

**Comment by kenjiuno** [comment]
Ok I have confirmed the issue you have identified.
I'll check it again.

**Comment by kenjiuno** [comment]
Hi please test https://www.nuget.org/packages/kenjiuno.PdfSharp.Xps/1.1.15 it should work

**Comment by tp1415926535** [comment]
> Hi please test https://www.nuget.org/packages/kenjiuno.PdfSharp.Xps/1.1.15 it should work

Yes it looks fixed, and cleaner than 1.12, no black thin lines on the sides.
