### ISSUE TITLE
Xps Opacity

### ISSUE THREAD

**Issue by davidgp15** [HiraokaHyperTools/PDFsharp#3]
Hi,

I´m evaluating the library and I have a problem. I have a xps file with an object that has a different opacity level and when I converted the file to pdf the file has the same opacity in all the objects.

If I print the xps to pdf using the "Microsoft Print to PDF" printer the result is the expected.

I attached the 3 files. The xps file, the wrong pdf and the printed pdf file.

[Documents.zip](https://github.com/HiraokaHyperTools/PDFsharp/files/2235423/Documents.zip)

**Comment by kenjiuno** [comment]
Thanks, I'll check about it.

**Comment by kenjiuno** [comment]
Hi.
This problem should be fixed (using your xps & pdf files for reference) in 067c09e9112d42fc891a49ca07227c8644929bb0

![image](https://user-images.githubusercontent.com/5955540/54968116-de16e880-4fbc-11e9-937b-4904b7dd3960.png)

NuGet package updated
https://www.nuget.org/packages/kenjiuno.PdfSharp.Xps/1.1.1

**Comment by kenjiuno** [comment]
I'll close this issue due to long time inactivity.
Please reopen or start new issue, if you still have problem...
