### ISSUE TITLE
Can not convert muliti page XPS file to PDF

### ISSUE THREAD

**Issue by yaozhong-OMEC** [HiraokaHyperTools/PDFsharp#4]
If the XPS file has muliti page, convert it will not get a right PDF.It will repeat the first page in muliti  times.Here is the sample XPS file and convert it to the PDF file.
[Sample.zip](https://github.com/HiraokaHyperTools/PDFsharp/files/3171523/Sample.zip)

**Comment by kenjiuno** [comment]
@yaozhong-OMEC Thanks for report, I'll check!

**Comment by kenjiuno** [comment]
should be fixed at 81b955cabaeb37b193f1e6396836822c358d2920

**Comment by kenjiuno** [comment]
nuget updated: 1.1.2 will come soon
https://www.nuget.org/packages/kenjiuno.PdfSharp.Xps/1.1.2

**Comment by yaozhong-OMEC** [comment]
Thanks a lot :)
