### ISSUE TITLE
Wrong list character in PDF output

### ISSUE THREAD

**Issue by t4rj4n** [HiraokaHyperTools/PDFsharp#9]
Hallo,

first thanks for this great library.

I tried to convert a FlowDocument (with a List) to a xps file and then to a pdf file.
The xps file is printed correctly in the xps viewer but the the list enumeration disc character is shown as a box in the corresponding pdf.

Looking into the files shows that, the disc character is unicode 0x009f using embedded Windings Font. This font seems to be embedded in the pdf too but the char is still displayed wrong.

Possible workarounds:

1. persuade XpsDocument not to use Wingdings?
2. Dont use FlowDocument List

**FlowDocument:**

`<FlowDocument Style="{DynamicResource {ComponentResourceKey TypeInTargetAssembly=mw:Styles, ResourceId=DocumentStyleKey}}" xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation" xmlns:mw="clr-namespace:Markdig.Wpf;assembly=Markdig.Wpf">
  <List MarkerStyle="Disc">
    <ListItem>
      <Paragraph>one</Paragraph>
    </ListItem>
  </List>
</FlowDocument>`

**Code for creating XpsDocument:**

`                var package = Package.Open(xpsStream, FileMode.Create);
                XpsDocument doc = new XpsDocument(package, CompressionOption.NotCompressed);
                var writer = XpsDocument.CreateXpsDocumentWriter(doc);
                var paginator = ((IDocumentPaginatorSource) flowDocument).DocumentPaginator;
                writer.Write(paginator);`

**Code for converting to pdf**

`PdfSharp.Xps.XpsConverter.Convert(xpsStream, pdfStream, false);
`

Xps and Pdf files:

[Test.zip](https://github.com/HiraokaHyperTools/PDFsharp/files/3636290/Test.zip)

Greetings from tarjan

**Comment by kenjiuno** [comment]
Hi @t4rj4n 
Thanks for reporting this issue!
I'll check about list item bullet thing!

**Comment by kenjiuno** [comment]
I have identified the problem part and fixed it!
https://www.nuget.org/packages/kenjiuno.PdfSharp.Xps/1.1.4 was pushed and available soon...

**Comment by kenjiuno** [comment]
Test.pdf is updated with latest PdfSharp, it will look nice!
[Test-fixed.zip](https://github.com/HiraokaHyperTools/PDFsharp/files/3639235/Test-fixed.zip)

**Comment by t4rj4n** [comment]
Thank you for fixing the bug that fast.
Works like a charm now.

Greetings from tarjan
